config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :categories
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
   
    root 'blogs#index'
    resources :blogs do
      resources :comments
  
     resources :comments do
      resources :replies
    end
    end
   
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	mount_uploader :image, ImageUploader
	mount_uploader :video, VideoUploader
	has_many :comments, dependent: :destroy
	has_many :images, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
  has_many :replies, dependent: :destroy
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :blog
	mount_uploader :image, ImageUploader

end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/reply.rb
class Reply < ApplicationRecord
	belongs_to :comment
  #has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	before_action :authenticate_user!
	def index
	  if params[:search].present? 
        @blogs= Blog.where('title LIKE ? OR description LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%") 
       elsif params[:start_date].present? && params[:end_date].present? 
        @blogs = Blog.where('created_at > ? AND created_at < ?', params[:start_date].to_date, params[:end_date].to_date)  
       else 
       @blogs=Blog.all 
     end
    end

	def new
		@blog=Blog.new
	end

	def create

		@blog=Blog.new(blog_params)
		@blog.save
        params[:blog][:image].each do |image|
          Image.create(:image=> image, blog_id: @blog.id)
        end   
		redirect_to @blog
	end

	def show
		@blog=Blog.find(params[:id])
    end

    def edit
        @blog = Blog.find(params[:id])
    end

    def update
        @blog = Blog.find(params[:id])
 
      if @blog.update(blog_params)
         redirect_to @blog
         else
         render 'edit'
        end
    end

    def destroy
        @blog = Blog.find(params[:id])
        @blog.destroy
 
        redirect_to blogs_path
    end
 

    private
    def blog_params
    params.require(:blog).permit(:title, :description, :image, :category_id,:video)
   end
end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base

  private

    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
	  @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.create(comment_params)
    redirect_to blog_path(@blog)
  end

   def edit
        @blog =Blog.find(params[:blog_id])
        @comment = Comment.find(params[:id])
    end

    def update
        @blog = Blog.find(params[:blog_id])
        @comment =Comment.find(params[:id])
  
         @comment.update(comment_params)
         redirect_to @blog
      
      end
 
  def destroy
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.find(params[:id])
    @comment.destroy
    redirect_to blog_path(@blog)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/products_controller.rb
class ProductsController < InheritedResources::Base

  private

    def product_params
      params.require(:product).permit(:name, :description)
    end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
	before_action do
    @comment = Comment.find(params[:comment_id])
  end

  # def index 
  #   byebug
  #   @replies = @comment.replies
  #   @reply = @comment.replies.new
  # end

  # def new
  #   @reply = @comment.replies.new
  # end

  def create
    @reply =  Reply.new(:body=> params[:replie][:body] ,:comment_id=> params[:replie][:comment_id] )
    @reply.save
    flash[:notice]= "replies created"
    redirect_to "/blogs/#{params[:blog_id]}"
    #redirect somewhere
  end
  # private
  #   def reply_params
  #     params.require(:reply).permit(:body)
  # end

end

 # before_action do
 #    @comment = Comment.find(params[:comment_id])
 #  end

 #  def index
 #    @replies = @comment.replies
 #    @reply = @comment.replies.new
 #  end

 #  def new
 #    @reply = @comment.replies.new
 #  end

 #  def create
 #    @reply = @comment.replies.new(reply_params)
 #    #redirect somewhere
 #  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>
 
<%= form_for @blog do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>
  <p>
  <%#=f.select :category_id,[['all', 1], ['co', 2],['view',3],['new',4]] %>
<%=f.select(:category_id, Category.all.collect {|u| [u.name, u.id]},:prompt => 'Select Category') %>
</p> 
 
  <p>
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </p>
  <p>
     <%= f.label :video %>
     <%=f.file_field :video%>

   </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', blog_path %>

app/views/blogs/index.html.erb
<h1>Listing blogs</h1>
 <%= link_to 'New blog', new_blog_path %>
<table class="table table-hover" >
   
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Category</th>
    <th>Image</th>
    <th>Video</th>
     <th colspan="3"></th>
  </tr>
 
  <% @blogs.each do |blog| %>
    <tr>
     <td><%= blog.title %></td>
     <td><%= blog.description %></td>

      <td>
       <%if blog.category_id.present? %> 
         <%= Category.find(blog.category_id).name %> 
        <% end %> 
      </td>

      <td>
       <%#=image_tag blog.image,  :size => "300x300", :contros => true %>
       
      </td>

      <td><%= image_tag blog.image_url(:thumb) if blog.image? %></td>
        
      <td>
       <%= video_tag blog.video, :size => "300x210", :controls => true %>
      </td>
       
      <td><%= link_to 'Show', blog_path(blog) %></td>
      <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
      <td><%= link_to 'Destroy', blog_path(blog),method: :delete,
      data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>

</table>

app/views/blogs/new.html.erb
<%= form_for :blog,url:blogs_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>
 
  <p>
    <%= f.label :image %><br>
    <%= f.file_field :image, multiple: true %>
  </p>
   <p>
     <%= f.label :video %>
     <%=f.file_field :video%>

   </p>

 <p>
  <%#=f.select :category_id,[['all', 1], ['co', 2],['view',3],['new',4]] %>
<%=f.select(:category_id, Category.all.collect {|u| [u.name, u.id]},:prompt => 'Select Category') %>
</p> 
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
 
  
<p>
 <%if @blog.category_id.present? %>
 <strong>Category:</strong>
 <%=Category.find(@blog.category_id).name%>
 <%end%>
</p>
  

<p>
 <strong>Title:</strong>
 <%= @blog.title %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @blog.description %>
</p>

<p>
 <strong>Image:</strong>
  <%@blog.images.each do |image|%>
  <%= image_tag image.image,multiple: true, :size => "300x300", :controls => true %>
  <%end%>
</p>


<p>
  
  <strong>Video:</strong>
  <%= video_tag @blog.video, :size => "320x240", :controls => true %>
</p>

<h2>Comments</h2>
<%= render @blog.comments %>
 
<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_blog_path(@blog) %>
<%= link_to 'Back', blogs_path %>

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>


<p>
<%= link_to 'Edit Comment', edit_blog_comment_path(@blog, comment)%>  ||

  <%= link_to 'Destroy Comment', [comment.blog, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %> 

</p>

<h2> reply a comment</h2>
<% @replies= Reply.where(:comment_id=> comment.id)
%>

<%@replies.each do |reply|%>
  <p>
  <strong>Reply:</strong>
  <%=reply.body%>
  </p>
<%end%>
<%= render 'replies/form', :comment=>comment %>

app/views/comments/_form.html.erb
<%= form_for([@blog, @blog.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/edit.html.erb
 <h> Edit Comment</h>

<%= form_for([@blog, @comment], :method => 'patch') do |f| %>

  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
   

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/replies/_form.html.erb
 <%= form_for :replie,url: "/blogs/#{@blog.id}/comments/#{comment.id}/replies" do |f| %>
   <%= f.hidden_field :comment_id,  :value=> comment.id %>
   <%= f.text_field :body %>
   <%= f.submit %>
<% end %>

app/views/replies/_reply.html.erb
<p>
<%= comment.body %>
<%= render comment.replies if comment.replies.any? %>
</p>